/**
 * Proves the TypeScript similarity engine (lib/similarity.ts) produces the
 * same output as the Python reference implementation (analysis/similarity.py)
 * for a representative set of real player-seasons.
 *
 * Fixture generated by analysis/ code directly (see the generation snippet
 * referenced in docs/qa.md) from public/data/similarity_pool.json, so this
 * test is exercising the exact same data the production app ships.
 */
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";
import { similarityIndex } from "../lib/similarity";

interface ParityPair {
  a_player_id: string;
  a_season: number;
  b_player_id: string;
  b_season: number;
  expected_similarity: number;
}

interface PoolEntry {
  player_id: string;
  season: number;
  vector: Record<string, number>;
}

const fixture: ParityPair[] = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, "similarity_parity_fixture.json"), "utf-8"),
);
const pool: PoolEntry[] = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, "../public/data/similarity_pool.json"), "utf-8"),
);

function findEntry(playerId: string, season: number): PoolEntry {
  const e = pool.find((p) => p.player_id === playerId && p.season === season);
  if (!e) throw new Error(`fixture references missing pool entry ${playerId} ${season}`);
  return e;
}

describe("Python/TypeScript similarity parity", () => {
  it("fixture is non-trivial", () => {
    expect(fixture.length).toBeGreaterThan(20);
  });

  for (const pair of fixture) {
    it(`${pair.a_player_id}(${pair.a_season}) vs ${pair.b_player_id}(${pair.b_season}) matches Python`, () => {
      const a = findEntry(pair.a_player_id, pair.a_season);
      const b = findEntry(pair.b_player_id, pair.b_season);
      const tsResult = similarityIndex(a.vector, b.vector);
      expect(tsResult).toBeCloseTo(pair.expected_similarity, 3);
    });
  }
});
